spring:
  application:
    name: flow
  data:
    redis:
      host: 127.0.0.1
      port: 6379

scheduler:
  enable: true


server:
  port: 9010
---
spring:
  config:
    activate:
      on-profile: test
  data:
    redis:
      port: 63790

scheduler:
  enable: false