spring:
  application:
    name: flow
  data:
    redis:
      host: 127.0.0.1
      port: 6379

scheduler:
  enable: true
  max-allow-user-count: 3  # 스케줄러가 한 번에 진입 허용할 최대 사용자 수

queue:
  max-capacity: 100  # 대기열 최대 용량 (0이면 무제한)
  ttl-seconds: 600  # 대기열 자동 만료 시간 (초, 0이면 만료 없음)
  token:
    max-age-seconds: 300  # 토큰 쿠키 만료 시간 (초)

server:
  port: 9010
---
spring:
  config:
    activate:
      on-profile: test
  data:
    redis:
      port: 63790

scheduler:
  enable: false
  max-allow-user-count: 3

queue:
  max-capacity: 5  # 테스트 환경에서는 용량을 5명으로 제한
  ttl-seconds: 3  # 테스트 환경에서는 TTL을 3초로 설정
  token:
    max-age-seconds: 300